project_name: logmanager

builds:
  - skip: true

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

milestones:
  - repo:
      owner: axiomhq
      name: logmanager
    close: true
    fail_on_error: false

release:
  github:
    owner: axiomhq
    name: logmanager
  prerelease: auto
  name_template: "Logmanager v{{.Version}}"
